### ISSUE TITLE
Problems after fresh install 

### ISSUE THREAD

**Issue by Snotmann** [Nico640/docker-unms#1]
Hey guys,

i got a problem on step 2 after a fresh install of these package:

...
unms_1  | {"name":"UNMS","hostname":"cc7e3b6f1498","pid":1084,"component":"os","level":20,"totalmem":"976MB","freemem":"28MB","loadavg":"2.7939453125, 2.11572265625, 2.13525390625","uptime":"1181758s","msg":"","time":"2019-08-02T07:21:43.732Z","v":0}
unms_1  | {"name":"UNMS","hostname":"cc7e3b6f1498","pid":1084,"component":"proc","level":20,"delay":"25.81ms","cpu":"22.84%","memory":"151MB","uptime":"216s","msg":"[api]","time":"2019-08-02T07:21:43.760Z","v":0}
unms_1  | {"name":"UNMS","hostname":"cc7e3b6f1498","pid":1084,"level":50,"err":{"message":"Uncaught error","name":"Error","stack":"Error: Uncaught error\n    at _error (/home/app/unms/node_modules/hapi/lib/protect.js:56:32)\n    at module.exports.internals.Protect.internals.Protect._onError (/home/app/unms/node_modules/hapi/lib/protect.js:38:16)\n    at Domain.emit (events.js:189:13)\n    at Domain.EventEmitter.emit (domain.js:441:20)\n    at Domain._errorHandler (domain.js:239:21)\n    at Object.setUncaughtExceptionCaptureCallback (domain.js:139:29)\n    at process._fatalException (internal/bootstrap/node.js:493:31)"},"msg":"[error] Uncaught error","time":"2019-08-02T07:21:43.770Z","v":0}
unms_1  | Debug: internal, implementation, error
unms_1  |     Error: Uncaught error
unms_1  |     at _error (/home/app/unms/node_modules/hapi/lib/protect.js:56:32)
unms_1  |     at module.exports.internals.Protect.internals.Protect._onError (/home/app/unms/node_modules/hapi/lib/protect.js:38:16)
unms_1  |     at Domain.emit (events.js:189:13)
unms_1  |     at Domain.EventEmitter.emit (domain.js:441:20)
unms_1  |     at Domain._errorHandler (domain.js:239:21)
unms_1  |     at Object.setUncaughtExceptionCaptureCallback (domain.js:139:29)
unms_1  |     at process._fatalException (internal/bootstrap/node.js:493:31)
unms_1  | {"name":"UNMS","hostname":"cc7e3b6f1498","pid":1084,"level":30,"msg":"[response] POST /nms/api/v2.1/nms/setup 500 (1143ms)","time":"2019-08-02T07:21:43.974Z","v":0}
unms_1  | {"name":"UNMS","hostname":"cc7e3b6f1498","pid":1084,"component":"scheduler","level":20,"task":"synchronizeSiteStatus","curr":"255.18 ms","avg":"26.02 ms","msg":"Finished task","time":"2019-08-02T07:21:43.981Z","v":0}
...

The message is that im not authorized for this action ?!

No idea what happen there

**Comment by Snotmann** [comment]
Ok after a reboot i works fine now ... my problem sorry
