### ISSUE TITLE
Node keeps on restarting

### ISSUE THREAD

**Issue by Mrc527** [Nico640/docker-unms#35]
Hello @Nico640 

I'm starting using your image but I keep on getting an issue. Some node stuff inside the image keeps on restarting.

Here is a log, I did not get anything out of it, to be honest. I hope you can understand a bit.

```
cat 2020-06-06T07_34_19_082Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/home/app/unms/npm', 'start' ]
2 info using npm@6.14.5
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle unms-server@1.2.0~prestart: unms-server@1.2.0
6 verbose lifecycle unms-server@1.2.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle unms-server@1.2.0~prestart: PATH: /home/app/unms/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/app/unms/node_modules/.bin:/home/app/unms/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/9.6/bin
8 verbose lifecycle unms-server@1.2.0~prestart: CWD: /home/app/unms
9 silly lifecycle unms-server@1.2.0~prestart: Args: [ '-c',
9 silly lifecycle   'yarn backup:apply && yarn migrate && yarn check-crm-db' ]
10 silly lifecycle unms-server@1.2.0~prestart: Returned: code: 0  signal: null
11 info lifecycle unms-server@1.2.0~start: unms-server@1.2.0
12 verbose lifecycle unms-server@1.2.0~start: unsafe-perm in lifecycle true
13 verbose lifecycle unms-server@1.2.0~start: PATH: /home/app/unms/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/app/unms/node_modules/.bin:/home/app/unms/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/9.6/bin
14 verbose lifecycle unms-server@1.2.0~start: CWD: /home/app/unms
15 silly lifecycle unms-server@1.2.0~start: Args: [ '-c', 'node --max_old_space_size=2048 index.js' ]
16 silly lifecycle unms-server@1.2.0~start: Returned: code: 132  signal: null
17 info lifecycle unms-server@1.2.0~start: Failed to exec start script
18 verbose stack Error: unms-server@1.2.0 start: `node --max_old_space_size=2048 index.js`
18 verbose stack Exit status 132
18 verbose stack     at EventEmitter.<anonymous> (/home/app/unms/npm/node_modules/npm-lifecycle/index.js:332:16)
18 verbose stack     at EventEmitter.emit (events.js:198:13)
18 verbose stack     at ChildProcess.<anonymous> (/home/app/unms/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at ChildProcess.emit (events.js:198:13)
18 verbose stack     at maybeClose (internal/child_process.js:982:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
19 verbose pkgid unms-server@1.2.0
20 verbose cwd /home/app/unms
21 verbose Linux 4.14.24-qnap
22 verbose argv "/usr/local/bin/node" "/home/app/unms/npm" "start"
23 verbose node v10.19.0
24 verbose npm  v6.14.5
25 error code ELIFECYCLE
26 error errno 132
27 error unms-server@1.2.0 start: `node --max_old_space_size=2048 index.js`
27 error Exit status 132
28 error Failed at the unms-server@1.2.0 start script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 132, true ]
```

It should be a clean installation with almost the standard docker-compose file you provided so I don't get why this is happening.

Ciao!
M

**Comment by Mrc527** [comment]
Installing version 1.1.7, I get no issues. Do you think it would be worth to try an upgrade, after full setup on version 1.1.7?

**Comment by Nico640** [comment]
I don't think upgrading would fix it. What device / architecture and OS are you running on? I'll try to reproduce it.

**Comment by Mrc527** [comment]
I'm using a QNAP NAS, using the ContainerStation.

Is it of any help?

**Comment by Nico640** [comment]
Hmm, could you take a look at the UNMS log and check if there's something more obvious there?
The log is located at /config/unms/logs/unms.log inside the container. You can also access it from the mapped /config volume.

**Comment by Nico640** [comment]
Closed due to inactivity.
