### ISSUE TITLE
Can't start container

### ISSUE THREAD

**Issue by XiaoHippo** [Nico640/docker-unms#39]
First of all, thank you for taking over the docker image.

I'm running this on a Synology with an ARM CPU (DS218), and I can't seem to get UNMS started. (I already have linuxserver/unifi-controller running on the machine.) This is how I created the container:

```
sudo docker create \
    --name=unms \
    -e TZ=America/Los_Angeles \
    -e PUBLIC_HTTPS_PORT=9443 \
    -e PUBLIC_WS_PORT=9443 \
    -p 9080:80 \
    -p 9443:443 \
    -p 2055:2055/udp \
    -v /volume1/Storage/docker/unms:/config \
    --restart unless-stopped \
    nico640/docker-unms
```

This is what's in unms/logs/unms.log.

```
Running docker-entrypoint npm start
Sentry release: 
Version: 1.2.6+56557f8079.2020-07-23T15:07:54+02:00
Waiting for database containers
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
Background append only file rewriting started
Restoring backups and/or running migrations
yarn run v1.21.1
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ yarn backup:apply && yarn migrate && yarn check-crm-db
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ node ./cli/apply-backup.js
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Listening for netflow packets on port 2055 (14 ms)","time":"2020-09-18T22:04:35.324Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Initializing database","time":"2020-09-18T22:04:35.334Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":50,"msg":"Failed to get DB schema version: relation \"version\" does not exist","time":"2020-09-18T22:04:35.429Z","v":0}
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ node ./cli/migrate.js
Extension 'uuid-ossp:1.1 installed.
Extension 'pgcrypto:1.3 installed.
Extension 'cube:1.2 installed.
Extension 'earthdistance:1.1 installed.
Extension 'unaccent:1.1 installed.
== 20170116111143-init.js (1.0.0): migrating =======
== 20170116111143-init.js: migrated (0.541s)
== 20170130091406-add-log-type.js (1.0.0): migrating =======
...
== 20200703091532-table-config-column-widths.js: migrated (0.031s)
== 20200716133613-remote-lldp-from-wlan-interfaces.js (1.2.6): migrating =======
== 20200716133613-remote-lldp-from-wlan-interfaces.js: migrated (0.023s)
Migrations finished in 88.732s
Setting database schema version to 1.2.6
Done
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ node cli/check-crm-db.js
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Database initialized (120238 ms)","time":"2020-09-18T22:06:35.571Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Initializing RabbitMQ","time":"2020-09-18T22:06:35.571Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"RabbitMQ initialized (133 ms)","time":"2020-09-18T22:06:35.704Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for managed networks change notifications at queue 'settings.networks.changed'","time":"2020-09-18T22:06:35.761Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for managed networks change notifications at queue 'settings.blacklist.changed'","time":"2020-09-18T22:06:35.777Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for site IP addresses change notifications at queue 'site.ips.changed'","time":"2020-09-18T22:06:35.790Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for device authorizations at queue 'device.*.authorized'","time":"2020-09-18T22:06:35.807Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for device authorizations at queue 'device.*.settings.changed'","time":"2020-09-18T22:06:35.822Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for settings change notifications at queue 'settings.changed'","time":"2020-09-18T22:06:35.837Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Subscribed for log verbosity change notifications at queue 'server.log.verbosity'","time":"2020-09-18T22:06:35.854Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"There are no managed networks in the database, using default list (6 ms) [ '10.0.0.0/8',\n  '100.64.0.0/10',\n  '172.16.0.0/12',\n  '192.168.0.0/16' ]","time":"2020-09-18T22:06:35.862Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Loaded blacklist from database (3 ms) []","time":"2020-09-18T22:06:35.870Z","v":0}
{"name":"netflow","hostname":"0308462e8ecd","pid":1375,"level":30,"msg":"Cannot determine UNMS IP address (6 ms)","time":"2020-09-18T22:06:35.891Z","v":0}
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
No data returned from the query.
Retrying in 10s
Checking CRM database schema version.
CRM database schema version is '1.2.6'.
Done in 227.07s.
Exec npm start with memory limit 604

> unms-server@1.2.6 prestart /home/app/unms
> yarn backup:apply && yarn migrate && yarn check-crm-db

yarn run v1.21.1
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ node ./cli/apply-backup.js
Done in 6.52s.
yarn run v1.21.1
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ node ./cli/migrate.js
Extension 'uuid-ossp:1.1 installed.
Extension 'pgcrypto:1.3 installed.
Extension 'cube:1.2 installed.
Extension 'earthdistance:1.1 installed.
Extension 'unaccent:1.1 installed.
Migrations finished in 0.184s
Setting database schema version to 1.2.6
Done
Done in 3.58s.
yarn run v1.21.1
warning You don't appear to have an internet connection. Try the --offline flag to use the cache for registry queries.
$ node cli/check-crm-db.js
Checking CRM database schema version.
CRM database schema version is '1.2.6'.
Done in 3.44s.

> unms-server@1.2.6 start /home/app/unms
> node --max_old_space_size=2048 index.js

{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Master 4578 is running","time":"2020-09-18T22:08:44.196Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Connected to SiriDB server version: 2.0.34","time":"2020-09-18T22:08:51.011Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"SiriDB database 'unms' does not exists. Creating...","time":"2020-09-18T22:08:51.015Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Connected to PostgreSQL server version: PostgreSQL 9.6.17 on aarch64-unknown-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit","time":"2020-09-18T22:08:51.106Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Registering plugins","time":"2020-09-18T22:08:52.913Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"message-hub","level":30,"msg":"Starting RabbitMQ connection watchdog","time":"2020-09-18T22:09:13.069Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Deleted transient tokens.","time":"2020-09-18T22:09:13.322Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Connected to Redis server version: 3.2.6","time":"2020-09-18T22:09:13.596Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Updating SSL certificate on Nginx for hostname 0308462e8ecd","time":"2020-09-18T22:09:13.680Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":50,"msg":"SSL cert update failed: Error: connect ECONNREFUSED 127.0.0.1:12345","time":"2020-09-18T22:09:13.801Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Updating nginx configuration.","time":"2020-09-18T22:09:13.882Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":50,"msg":"Home page update failed: Error: connect ECONNREFUSED 127.0.0.1:12345","time":"2020-09-18T22:09:13.898Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"94MB","loadavg":"2.07177734375, 1.8984375, 1.46044921875","uptime":"12655s","msg":"","time":"2020-09-18T22:09:15.801Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"Plugin registration finished","time":"2020-09-18T22:09:16.859Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":30,"msg":"HTTP Server listening on http://0308462e8ecd:8081","time":"2020-09-18T22:09:16.920Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":50,"err":{"message":"getaddrinfo EAI_AGAIN fw-update.ubnt.com fw-update.ubnt.com:443","name":"RequestError","stack":"RequestError: getaddrinfo EAI_AGAIN fw-update.ubnt.com fw-update.ubnt.com:443\n    at ClientRequest.request.once.error (/home/app/unms/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/home/app/unms/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","code":"EAI_AGAIN"},"msg":"Failed to download latest firmware","time":"2020-09-18T22:09:17.905Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":5124,"level":30,"msg":"Worker 5124 started","time":"2020-09-18T22:09:19.942Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":5124,"component":"ws","level":30,"msg":"WS server running at ws://:::8082","time":"2020-09-18T22:09:30.119Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":50,"err":{"message":"getaddrinfo EAI_AGAIN unms.com unms.com:443","name":"RequestError","stack":"RequestError: getaddrinfo EAI_AGAIN unms.com unms.com:443\n    at ClientRequest.request.once.error (/home/app/unms/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/home/app/unms/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","code":"EAI_AGAIN"},"msg":"Failed to fetch latest UNMS version from remote server.","time":"2020-09-18T22:09:44.142Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"107MB","loadavg":"1.59423828125, 1.8095703125, 1.4443359375","uptime":"12685s","msg":"","time":"2020-09-18T22:09:45.801Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":50,"err":{"message":"getaddrinfo EAI_AGAIN fw-update.ubnt.com fw-update.ubnt.com:443","name":"RequestError","stack":"RequestError: getaddrinfo EAI_AGAIN fw-update.ubnt.com fw-update.ubnt.com:443\n    at ClientRequest.request.once.error (/home/app/unms/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/home/app/unms/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","code":"EAI_AGAIN"},"msg":"Failed to download latest firmware","time":"2020-09-18T22:09:46.759Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"level":50,"err":{"message":"getaddrinfo EAI_AGAIN blog.ui.com blog.ui.com:443","name":"RequestError","stack":"RequestError: getaddrinfo EAI_AGAIN blog.ui.com blog.ui.com:443\n    at ClientRequest.request.once.error (/home/app/unms/node_modules/got/source/request-as-event-emitter.js:178:14)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at ClientRequest.EventEmitter.emit (domain.js:448:20)\n    at ClientRequest.origin.emit.args (/home/app/unms/node_modules/@szmarczak/http-timer/source/index.js:37:11)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at TLSSocket.emit (events.js:198:13)\n    at TLSSocket.EventEmitter.emit (domain.js:448:20)\n    at emitErrorNT (internal/streams/destroy.js:91:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","code":"EAI_AGAIN"},"msg":"Failed to update blog feed","time":"2020-09-18T22:09:49.820Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"135MB","loadavg":"1.16455078125, 1.68310546875, 1.41357421875","uptime":"12715s","msg":"","time":"2020-09-18T22:10:15.801Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"103MB","loadavg":"0.9892578125, 1.595703125, 1.390625","uptime":"12745s","msg":"","time":"2020-09-18T22:10:45.801Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"160MB","loadavg":"0.99462890625, 1.53759765625, 1.3759765625","uptime":"12775s","msg":"","time":"2020-09-18T22:11:15.802Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"181MB","loadavg":"0.99755859375, 1.48486328125, 1.361328125","uptime":"12805s","msg":"","time":"2020-09-18T22:11:45.802Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"193MB","loadavg":"0.80810546875, 1.3896484375, 1.33349609375","uptime":"12835s","msg":"","time":"2020-09-18T22:12:15.802Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"169MB","loadavg":"0.681640625, 1.30322265625, 1.30615234375","uptime":"12865s","msg":"","time":"2020-09-18T22:12:45.803Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"141MB","loadavg":"0.619140625, 1.2255859375, 1.2783203125","uptime":"12895s","msg":"","time":"2020-09-18T22:13:15.803Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"104MB","loadavg":"0.93017578125, 1.23583984375, 1.279296875","uptime":"12925s","msg":"","time":"2020-09-18T22:13:45.803Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"176MB","loadavg":"1.353515625, 1.30859375, 1.30078125","uptime":"12955s","msg":"","time":"2020-09-18T22:14:15.803Z","v":0}
{"name":"UNMS","hostname":"0308462e8ecd","pid":4578,"component":"os","level":30,"totalmem":"1864MB","freemem":"131MB","loadavg":"1.037109375, 1.2314453125, 1.27392578125","uptime":"12985s","msg":"","time":"2020-09-18T22:14:45.803Z","v":0}
```

**Comment by XiaoHippo** [comment]
Umm, I think this is because I'm running docker in --network=host mode. This is a limitation with my particular Synology I think. Is there a way this container would still work?

**Comment by Nico640** [comment]
Seems like UNMS is starting but the container doesn't have a network / internet connection. Could you confirm that by trying to ping a website / a device in your local network from the container?

**Comment by XiaoHippo** [comment]
I think this is because there's no bridge interface in my docker, which I had to disable due to the Synology limitation. I can, however, run a few other containers in "host" mode.

But when I added --network=host when I created this container, then it seemed it wouldn't connect to postgres due to: FATAL: no pg_hba.conf entry for host"127.0.0.1", user"unms", database"unms".

**Comment by Nico640** [comment]
As far as I know, port remapping (-p parameter) doesn't work when using host mode, so the container would try to bind port 80, 443, 2055 to the IP address of your Synology, but these ports are probably in use. If they really are in use by something else (web gui? I'm not familar with Synology), you could build your own container image from source and change the ports in the dockerfile (WS_PORT, PUBLIC_HTTPS_PORT, PUBLIC_WS_PORT, EXPOSE), and in the root/etc/services.d/nginx/run file (HTTP_PORT, HTTPS_PORT) to match the ones you want (9080, 9443).

**Comment by XiaoHippo** [comment]
Yeah, I believe that could be the issue. I'll rebuild my image, and report back what I find. Thanks.

**Comment by XiaoHippo** [comment]
OK so in addition to 80 and 443, postgres' 5432 is also in conflict. Once *I think* I've changed all these ports, running /init eventually gave me this error repeatedly:

{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2020-09-19T18:27:54-07:00","severity":"WARNING","level":300}
Makefile:12: recipe for target 'server_with_migrate' failed
make: *** [server_with_migrate] Error 1

No go :(

**Comment by Nico640** [comment]
That looks like UCRM waiting for UNMS to start. Did you take a look at the UNMS logs?

**Comment by XiaoHippo** [comment]
This is UNMS:
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Master 3202 is running","time":"2020-09-20T17:03:54.827Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Connected to SiriDB server version: 2.0.34","time":"2020-09-20T17:04:00.816Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"SiriDB database 'unms' does not exists. Creating...","time":"2020-09-20T17:04:00.819Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Connected to PostgreSQL server version: PostgreSQL 9.6.17 on aarch64-unknown-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit","time":"2020-09-20T17:04:00.951Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Registering plugins","time":"2020-09-20T17:04:02.790Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"component":"message-hub","level":30,"msg":"Starting RabbitMQ connection watchdog","time":"2020-09-20T17:04:19.550Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Deleted transient tokens.","time":"2020-09-20T17:04:19.773Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Connected to Redis server version: 3.2.6","time":"2020-09-20T17:04:20.053Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Updating SSL certificate on Nginx for hostname DS218","time":"2020-09-20T17:04:20.144Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"SSL cert for 'DS218' updated successfully","time":"2020-09-20T17:04:20.593Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Updating nginx configuration.","time":"2020-09-20T17:04:20.661Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Nginx configuration updated successfully. Home page set to unms, ucrm enabled'","time":"2020-09-20T17:04:21.124Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"Plugin registration finished","time":"2020-09-20T17:04:23.943Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"level":30,"msg":"HTTP Server listening on http://DS218:8081","time":"2020-09-20T17:04:24.002Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"component":"os","level":30,"totalmem":"1864MB","freemem":"175MB","loadavg":"2.40478515625, 1.60302734375, 1.353515625","uptime":"167164s","msg":"","time":"2020-09-20T17:04:24.826Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3482,"level":30,"msg":"Worker 3482 started","time":"2020-09-20T17:04:27.721Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3482,"component":"ws","level":30,"msg":"WS server running at ws://:::8082","time":"2020-09-20T17:04:44.521Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"component":"os","level":30,"totalmem":"1864MB","freemem":"503MB","loadavg":"2.7861328125, 1.77001953125, 1.41748046875","uptime":"167196s","msg":"","time":"2020-09-20T17:04:57.249Z","v":0}
{"name":"UNMS","hostname":"DS218","pid":3202,"component":"os","level":30,"totalmem":"1864MB","freemem":"526MB","loadavg":"2.162109375, 1.69873046875, 1.4033203125","uptime":"167226s","msg":"","time":"2020-09-20T17:05:27.249Z","v":0}

And this is UCRM:
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-09-20T10:11:08-07:00","severity":"INFO","level":200}
{"message":"Waiting for UNMS (127.0.0.1:8081).","channel":"unms_ready.sh","datetime":"2020-09-20T10:11:12-07:00","severity":"INFO","level":200}
{"message":"UNMS did not start in time, restarting container.","channel":"web.sh","datetime":"2020-09-20T10:11:13-07:00","severity":"WARNING","level":300}

I think UNMS is started on DS218:8081 which has a 192.168.x address, but UCRM is listening on 127.0.0.1:8081. This might be the problem?

**Comment by XiaoHippo** [comment]
The port situation in host mode is a total mess. I think I'm giving up at the moment, but probably will try to write a script to collect basic EdgeOS stats from its websocket, which might be easier...

**Comment by Nico640** [comment]
Yeah the container image is pretty crammed when considering that the standard UNMS install has 9 individual containers.
UNMS seems to start, but as you said, UCRM doesn't seem to communicate with UNMS. I assume you already changed the UNMS_HOST variable in the root/etc/services.d/ucrm/run file? You could also try to wget the UNMS port and see if you get a response.

**Comment by XiaoHippo** [comment]
I played around and UNMS wasn't online, but I couldn't figure out why.
Thanks a lot for your help though.

**Comment by XiaoHippo** [comment]
I think I won this whack-a-moe game and got this working on a host network. This is what I did, without rebuilding everything:

Run the container in interactive mode with reconfigured ports:
```
sudo docker run \
    -i -t \
    --name=unms \
    --network=host \
    -e TZ=America/Los_Angeles \
    -e PUBLIC_HTTPS_PORT=7443 \
    -e PUBLIC_WS_PORT=7443 \
    -e HTTPS_PORT=7443 \
    -e WS_PORT=7443 \
    -e MEM_LIMIT=1024M `#optional` \
    -v /dev:/dev \
    -v /volume1/Storage/docker/unms:/config \
    --entrypoint bash \
    nico640/docker-unms
```
When the container is up, update ports like this:
```
sed -i 's/#port = 5432/port = 6432/g'     /config/postgres/postgresql.conf
sed -i 's/5432/6432/g'                    /etc/postgresql/9.6/main/postgresql.conf
sed -i 's/5432/6432/g'                    /etc/services.d/netflow/run
sed -i 's/5432/6432/g'                    /etc/services.d/ucrm/run
sed -i 's/5432/6432/g'                    /etc/services.d/unms/run
sed -i 's/5432/6432/g'                    /tmp/crontabs/server
sed -i 's/ HTTP_PORT=80/ HTTP_PORT=7080/' /etc/services.d/nginx/run
sed -i 's/-80}/-7080}/g'                  /refresh-configuration.sh
sed -i 's/-81}/-7081}/g'                  /refresh-configuration.sh
sed -i 's/=443/=7443/g'                   /etc/services.d/nginx/run
sed -i 's/-443}/-7443}/g'                 /refresh-configuration.sh
```
Test it by running `/init`. Once done, commit the image with a new entrypoint to '/init'. It seems UCRM still doesn't quite work, but I don't need that.

**Comment by Nico640** [comment]
I'm glad you managed to get it running ;)

Closing due to inactivity.
