### ISSUE TITLE
UISP container starts only after recreation, but than not and have to recreate container every time  

### ISSUE THREAD

**Issue by Roberto6969** [Nico640/docker-unms#94]
Hello,
after restore from backup, UISP start normally, but next start will not. There is some errors in log, but I'm not sure if errors are critical:

[W 2023-07-31 07:34:59] Error handling manage request: database directory already exists: /config/siridb/unms/
Migration failed: SiriDbError: database directory already exists: /config/siridb/unms/
    at SiriDbConnection.resolveRequest (/home/app/unms/lib/siridb/connection.js:200:25)
    at SiriDbConnection.handleData (/home/app/unms/lib/siridb/connection.js:151:22)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  tp: 96
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023-07-31 07:35:00.231 UTC [1367] FATAL:  role "root" does not exist 

Is there any error which should be solved?

Thank You!

**Comment by Nico640** [comment]
Hi,
Yes, I'm pretty sure that the SiriDB error will prevent UISP from starting. The SiriDB database might be corrupt, can you look through the logs if there are any different errors related to SiriDB? Given that you have backups and because SiriDB didn't contain any critical data last time I checked (I think it only contains statistics), you can try to stop the container and delete the `/config/siridb` directory (`/config` should be mapped to a directory on your drive), then start the container and check if UISP starts and if all your data is still there.

**Comment by Roberto6969** [comment]
Hi,
Thank you for your answer. My directory structure is slightly different due to docker environment. Instead of
_/config/siridb_ I have
_/user/unms/volumes/unms/siridb_

You're right. SiriDB prevented UISP to start. But it was pretty stupid reason. I've ran out with disk space temporary every night. In this time UISP (SiriDB, I believe) crashed. Until I didn't delete /siridb directory and restart UISP, UISP could not start. 

Thank You for your help.
